# Google Cloud Build configuration for Yodelstar
# This file enables automated deployment via Cloud Build

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/yodelstar-app:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/yodelstar-app:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/yodelstar-app:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/yodelstar-app:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'yodelstar',
      '--image', 'gcr.io/$PROJECT_ID/yodelstar-app:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--port', '8080',
      '--timeout', '300',
      '--set-env-vars', 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
    ]

# Substitution variables (set these in Cloud Build trigger)
substitutions:
  _GEMINI_API_KEY: 'your-gemini-api-key-here'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s' 